// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OdeUIClient is the client API for OdeUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OdeUIClient interface {
	// ListAnalysisSpecs returns a list of Image Analysis that can be started through the UI.
	ListAnalysisSpecs(ctx context.Context, in *ListAnalysisSpecsRequest, opts ...grpc.CallOption) (OdeUI_ListAnalysisSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type odeUIClient struct {
	cc grpc.ClientConnInterface
}

func NewOdeUIClient(cc grpc.ClientConnInterface) OdeUIClient {
	return &odeUIClient{cc}
}

func (c *odeUIClient) ListAnalysisSpecs(ctx context.Context, in *ListAnalysisSpecsRequest, opts ...grpc.CallOption) (OdeUI_ListAnalysisSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &OdeUI_ServiceDesc.Streams[0], "/v1.OdeUI/ListAnalysisSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &odeUIListAnalysisSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OdeUI_ListAnalysisSpecsClient interface {
	Recv() (*ListAnalysisSpecsResponse, error)
	grpc.ClientStream
}

type odeUIListAnalysisSpecsClient struct {
	grpc.ClientStream
}

func (x *odeUIListAnalysisSpecsClient) Recv() (*ListAnalysisSpecsResponse, error) {
	m := new(ListAnalysisSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *odeUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.OdeUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OdeUIServer is the server API for OdeUI service.
// All implementations must embed UnimplementedOdeUIServer
// for forward compatibility
type OdeUIServer interface {
	// ListAnalysisSpecs returns a list of Image Analysis that can be started through the UI.
	ListAnalysisSpecs(*ListAnalysisSpecsRequest, OdeUI_ListAnalysisSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedOdeUIServer()
}

// UnimplementedOdeUIServer must be embedded to have forward compatible implementations.
type UnimplementedOdeUIServer struct {
}

func (UnimplementedOdeUIServer) ListAnalysisSpecs(*ListAnalysisSpecsRequest, OdeUI_ListAnalysisSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListAnalysisSpecs not implemented")
}
func (UnimplementedOdeUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedOdeUIServer) mustEmbedUnimplementedOdeUIServer() {}

// UnsafeOdeUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OdeUIServer will
// result in compilation errors.
type UnsafeOdeUIServer interface {
	mustEmbedUnimplementedOdeUIServer()
}

func RegisterOdeUIServer(s grpc.ServiceRegistrar, srv OdeUIServer) {
	s.RegisterService(&OdeUI_ServiceDesc, srv)
}

func _OdeUI_ListAnalysisSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListAnalysisSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OdeUIServer).ListAnalysisSpecs(m, &odeUIListAnalysisSpecsServer{stream})
}

type OdeUI_ListAnalysisSpecsServer interface {
	Send(*ListAnalysisSpecsResponse) error
	grpc.ServerStream
}

type odeUIListAnalysisSpecsServer struct {
	grpc.ServerStream
}

func (x *odeUIListAnalysisSpecsServer) Send(m *ListAnalysisSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _OdeUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OdeUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.OdeUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OdeUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OdeUI_ServiceDesc is the grpc.ServiceDesc for OdeUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OdeUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.OdeUI",
	HandlerType: (*OdeUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _OdeUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListAnalysisSpecs",
			Handler:       _OdeUI_ListAnalysisSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ode-ui.proto",
}
