#!/usr/bin/env bash

# Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Script for updating copyright headers across the code

if $(sed --version 2>/dev/null | head -n1 | grep -q "GNU");
then
  echo "GNU version"
  inplace_sed() { sed -i -e "$@"; }
else
  echo "FreeBSD version"
  inplace_sed(){ sed -i "" -e "$@"; }
fi

COPYRIGHTS=( "Copyright (c) " "Copyright © " )
YEAR="[0-9]\{4\}"
RANGE=" - "
AUTHOR=" Bhojpur Consulting Private Limited, India"
CURRENT_YEAR=${1:-$(date +%Y)}
echo "Updating copyright with $CURRENT_YEAR"

# Update year range copyrights
for COPYRIGHT in "${COPYRIGHTS[@]}";
do
    echo "Updating $COPYRIGHT"
    for file in $(git grep -l "${COPYRIGHT}${YEAR}${RANGE}${YEAR}${AUTHOR}");
    do
        inplace_sed "s/\(${COPYRIGHT}${YEAR}${RANGE}\)${YEAR}\(${AUTHOR}\)/\1${CURRENT_YEAR}\2/" $file
    done

    # Update single year copyrights
    for file in $(git grep -l "${COPYRIGHT}${YEAR}${AUTHOR}");
    do
        if [ -z "$(git grep "${COPYRIGHT}${CURRENT_YEAR}${AUTHOR}" -- $file)" ];
        then
            inplace_sed "s/\(${COPYRIGHT}${YEAR}\)\(${AUTHOR}\)/\1${RANGE}${CURRENT_YEAR}\2/" $file
        fi
    done
done

echo "Updating pom.xml"
inplace_sed "s/<year>${YEAR}/<year>${CURRENT_YEAR}/" pom.xml
